/**
 * Loader for the bundled Tier-1 persona previews.
 *
 * The previews live at `apps/desktop/public/personas-previews/` and
 * are generated by `tools/build-persona-previews/build.py`. They ship
 * with the desktop app (Vite copies `public/` into the frontend dist;
 * Tauri 2 then bundles dist/ into the installer), so the wizard can
 * render the cast offline before the user commits to a Tier-2
 * download.
 *
 * See file:///C:/Users/dbhav/Projects/aether/docs/adr/ADR-0012-persona-delivery-download-on-demand.md
 * for the delivery-tier model.
 */

export interface PersonaPreview {
  slug: string;
  display_name: string;
  tagline: string;
  archetype: string;
  /** Path relative to /personas-previews/, e.g. "aurora/preview.webp" */
  preview_webp: string;
  /** Path relative to /personas-previews/, e.g. "aurora/preview_voice.opus" */
  preview_voice_opus: string;
}

interface PersonaPreviewIndex {
  schema_version: number;
  personas: PersonaPreview[];
}

const INDEX_PATH = "/personas-previews/index.json";

/**
 * Build the absolute URL the webview can fetch for a given relative
 * preview-asset path. Wrapped so future Tauri-asset-protocol migration
 * has one site to update.
 */
export function previewAssetUrl(relativePath: string): string {
  return `/personas-previews/${relativePath}`;
}

/**
 * Fetch the bundled preview catalog. Throws on network or schema
 * failure — caller is responsible for surfacing a wizard-blocking
 * error in that case (the wizard should not silently render an
 * empty cast).
 */
export async function loadPersonaPreviews(): Promise<PersonaPreview[]> {
  const resp = await fetch(INDEX_PATH);
  if (!resp.ok) {
    throw new Error(
      `failed to fetch persona preview index: ${resp.status} ${resp.statusText}`,
    );
  }
  const body = (await resp.json()) as PersonaPreviewIndex;
  if (!body || typeof body !== "object" || !Array.isArray(body.personas)) {
    throw new Error(
      "persona preview index has unexpected shape (missing `personas` array)",
    );
  }
  return body.personas.map((p) => {
    if (!p.slug || !p.display_name || !p.archetype) {
      throw new Error(
        `persona preview entry missing required fields: ${JSON.stringify(p)}`,
      );
    }
    return p;
  });
}
