//! # aether-event-bus
//!
//! Typed cross-layer event substrate for Aether. **Wave 1 scaffold — no logic.**
//!
//! Canonical reference: `ARCHITECTURE.md` (the cross-layer event surface and
//! layer boundaries).
//!
//! ## Invariants (enforced in later waves)
//!
//! 1. Every event carries `change_id`, `seq: u64`, `source_layer`.
//! 2. Rust enum surface is canonical; TS bindings are generated by
//!    `tools/ts-bindings-gen/`.
//! 3. Sibling layers do not import each other — they subscribe to the bus.
//! 4. High-frequency events stay Rust-internal (`Projected::Internal`) and
//!    are not bridged to the Tauri webview verbatim.

#![deny(unsafe_code)]
#![warn(missing_docs)]

use serde::{Deserialize, Serialize};

/// Layer tag carried by every event for audit and boundary enforcement.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SourceLayer {
    /// L1 — Interaction / timing / reflex.
    L1,
    /// L2 — Memory kernel.
    L2,
    /// L3 — Presence engine.
    L3,
    /// L4 — Model router.
    L4,
    /// L5 — Policy / authorization.
    L5,
    /// L6 — Persona compiler.
    L6,
    /// L7 — Trust UX / onboarding.
    L7,
    /// Media pipeline (STT/TTS/VAD).
    Media,
    /// Core (health, bus, lifecycle).
    Core,
}

/// Projection flag — does the event cross the Tauri IPC bridge to the webview?
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Projected {
    /// Stays inside the Rust runtime.
    Internal,
    /// Bridged verbatim to the webview channel.
    Full,
    /// Bridged via coalesced low-frequency summary.
    Coalesced,
    /// Bridged on-demand only (request/reply pattern).
    OnDemand,
}

/// Envelope every bus event is wrapped in.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventEnvelope<P> {
    /// ULID correlating all events in one causal chain.
    pub change_id: String,
    /// Bus-global monotonic counter; subscribers track per-channel high-water-mark.
    pub seq: u64,
    /// Source layer tag.
    pub source_layer: SourceLayer,
    /// Projection flag.
    pub projected: Projected,
    /// Canonical snake_case event name (e.g. `policy_decision`).
    pub name: &'static str,
    /// Typed payload.
    pub payload: P,
}

/// Errors returnable by the bus. Shape will expand in Wave 2+.
#[derive(Debug, thiserror::Error)]
pub enum BusError {
    /// Subscriber detected a gap in `seq` and must replay.
    #[error("sequence gap detected on channel {channel}: last={last}, got={got}")]
    SequenceGap {
        /// Channel name.
        channel: &'static str,
        /// Last seen sequence.
        last: u64,
        /// Just-received sequence.
        got: u64,
    },
    /// Subscriber back-pressure — bus dropped the event.
    #[error("subscriber backpressure dropped event on channel {channel}")]
    Backpressure {
        /// Channel name.
        channel: &'static str,
    },
    /// Internal placeholder for unimplemented Wave 1 surface.
    #[error("not yet implemented — Wave 2+")]
    NotImplemented,
}

// TODO(wave-2): introduce per-layer payload enums (L1Event, L2Event, ...) and a
// top-level `BusEvent` sum. Source: event_contracts_master.md §3 onward.
// TODO(wave-2): tokio broadcast channel per `SourceLayer` with replayable cursor.
// TODO(wave-2): `ts-rs` derive on every payload struct so bindings generate
// cleanly into `packages/types/`.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn source_layer_round_trips() {
        let json = serde_json::to_string(&SourceLayer::L5).unwrap();
        let back: SourceLayer = serde_json::from_str(&json).unwrap();
        assert_eq!(back, SourceLayer::L5);
    }
}
