// @aether/types — Wave 1 placeholder
//
// This file will be REGENERATED by tools/ts-bindings-gen/ from Rust structs in
// packages/event-bus, packages/storage, and every packages/l*-* crate. Do NOT
// hand-edit these types after the generator lands in Wave 2+.
//
// Canonical source:
//   ARCHITECTURE.md
//
// Hand-written stubs below mirror the Rust shapes in
// packages/event-bus/src/lib.rs so downstream TS packages can start compiling
// against a real module. Replace wholesale when the generator is wired.

export type SourceLayer =
  | "L1"
  | "L2"
  | "L3"
  | "L4"
  | "L5"
  | "L6"
  | "L7"
  | "Media"
  | "Core";

export type Projected = "Internal" | "Full" | "Coalesced" | "OnDemand";

export interface EventEnvelope<P> {
  change_id: string;
  seq: number;
  source_layer: SourceLayer;
  projected: Projected;
  name: string;
  payload: P;
}

/** Marker — every hand-written entry in this file is a placeholder until codegen. */
export const WAVE1_PLACEHOLDER = true as const;
